version: "3"

services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: nest
      POSTGRES_PASSWORD: nest
      POSTGRES_DB: nest
    ports:
      - "5432:5432"